CC = gcc
CFLAGS = -O2 -Wall -Wextra

# Define the target executable name
TARGET = PA5-finalCode

# Define the source files
SRC = PA5-finalCode.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)